import { describe, expect, it } from 'vitest'
import {
  parseClaudeSessionContent,
  createClaudeSessionResumeState
} from '../ai-vault/session-scanner-primary-parsers'
import { parseCodexSessionContent } from '../ai-vault/session-scanner-codex-parser'
import { refreshCodexTitleFromIndex } from '../ai-vault/session-scanner-codex-cached-title'
import { parseAiVaultSessionTitlesResult } from '../ai-vault/session-title-result-validation'
import { retainConfirmedProviderName } from '../../shared/session-names/session-name-contract'

const file = { path: '/fixture/session.jsonl', mtimeMs: 1, modifiedAt: '2026-09-09T00:00:00Z' }
const lines = (records: unknown[]) => records.map((record) => JSON.stringify(record)).join('\n')
const claudeUser = (content: string) => ({
  type: 'user',
  sessionId: 'session',
  message: { content }
})
const codexUser = (message: string) => ({
  type: 'event_msg',
  payload: { type: 'user_message', message }
})
const meta = { type: 'session_meta', payload: { id: 'session', title: 'Old metadata name' } }

describe('native name evidence through production parsers', () => {
  it('does not call a Claude task prompt a provider name', async () => {
    const session = await parseClaudeSessionContent(
      file,
      lines([
        claudeUser('继续'),
        claudeUser('运行测试'),
        claudeUser('好的'),
        claudeUser('修复其他功能')
      ]),
      'linux',
      { executionHostId: 'ssh:fixture' }
    )
    expect(session).toMatchObject({ providerName: { kind: 'absent' }, generatedTitle: '运行测试' })
  })

  it('uses explicit Claude name records, preserving short native names', async () => {
    const session = await parseClaudeSessionContent(
      file,
      lines([
        claudeUser('运行测试'),
        { type: 'agent-name', agentName: 'Worker label' },
        { type: 'ai-title', aiTitle: 'Generated by provider' },
        { type: 'custom-title', customTitle: '继续' }
      ]),
      'linux',
      { executionHostId: 'ssh:fixture' }
    )
    expect(session).toMatchObject({
      providerName: { kind: 'named', title: '继续', field: 'custom-title.customTitle' },
      generatedTitle: '运行测试'
    })
  })

  it('keeps the same first eligible task when resuming an append-only fold', async () => {
    const fold = createClaudeSessionResumeState(file)
    fold.consumeLine(JSON.stringify(claudeUser('好的')))
    expect(
      (await fold.finalize('linux', { executionHostId: 'ssh:fixture' }))?.generatedTitle
    ).toBeNull()
    fold.consumeLine(JSON.stringify(claudeUser('检查登录异常')))
    fold.consumeLine(JSON.stringify(claudeUser('继续')))
    expect((await fold.finalize('linux', { executionHostId: 'ssh:fixture' }))?.generatedTitle).toBe(
      '检查登录异常'
    )
  })

  it('Codex current index outranks stale metadata on cold parse and warm reuse', async () => {
    const session = await parseCodexSessionContent({
      file,
      content: lines([meta, codexUser('运行测试')]),
      readIndexedTitle: async () => 'Current provider name'
    })
    expect(session).toMatchObject({
      providerName: {
        kind: 'named',
        title: 'Current provider name',
        field: 'session_index.thread_name'
      },
      generatedTitle: '运行测试'
    })
    const refreshed = await refreshCodexTitleFromIndex(session!, async () => 'Renamed later')
    expect(refreshed.providerName).toEqual({
      kind: 'named',
      title: 'Renamed later',
      field: 'session_index.thread_name'
    })
  })

  it('Codex prompt fallback is distinct from native absence', async () => {
    const session = await parseCodexSessionContent({
      file,
      content: lines([
        { type: 'session_meta', payload: { id: 'session' } },
        codexUser('继续'),
        codexUser('运行测试')
      ]),
      readIndexedTitle: async () => null
    })
    expect(session).toMatchObject({ providerName: { kind: 'absent' }, generatedTitle: '运行测试' })
  })

  it('keeps evidence across a paired-host result, including missing legacy titles', () => {
    const result = {
      titles: [],
      nameEvidence: [
        { agent: 'claude', sessionId: 'session', providerName: { kind: 'unavailable' } }
      ]
    }
    expect(parseAiVaultSessionTitlesResult(result)).toEqual(result)
    expect(
      parseAiVaultSessionTitlesResult({
        titles: [{ agent: 'codex', sessionId: 'session', title: 'legacy' }]
      })
    ).toEqual({ titles: [{ agent: 'codex', sessionId: 'session', title: 'legacy' }] })
  })

  it('only positive rename or explicit revocation changes a confirmed name', () => {
    const previous = {
      kind: 'named' as const,
      title: 'Known name',
      field: 'custom-title.customTitle'
    }
    for (const kind of ['absent', 'unavailable'] as const) {
      expect(retainConfirmedProviderName(previous, { kind })).toBe(previous)
    }
    expect(retainConfirmedProviderName(previous, { kind: 'cleared' })).toEqual({ kind: 'cleared' })
    expect(
      retainConfirmedProviderName(previous, {
        kind: 'named',
        title: 'New name',
        field: 'custom-title.customTitle'
      })
    ).toMatchObject({ title: 'New name' })
  })
})
